### ISSUE TITLE
Component not found: stream_server.

### ISSUE THREAD

**Issue by jmartens** [oxan/esphome-stream-server#17]
Below minimal configuration file fails validation and build on my ESPHome instance:.

```
INFO Reading configuration /config/esphome/test123.yaml...
Failed config

stream_server: [source /config/esphome/test123.yaml:14]
  
  Component not found: stream_server.
```

test123.yaml:
```
---
substitutions:
  devicename: test123
  upper_devicename: "TEST123"

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

external_components:
  - source: github://oxan/esphome-stream-server

stream_server:
```

I am using the following installation:

## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 8.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (10.0.2), Studio Code Server (4.1.0), Portainer (2.11.0-3), ESPHome (2022.2.5)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>
