### ISSUE TITLE
can use muti serial?

### ISSUE THREAD

**Issue by raxel0510** [oxan/esphome-stream-server#23]
ESP32 have 3 uart
can use
uart1  port:5000
uart2  port:5001???

**Comment by RoganDawes** [comment]
It is definitely possible to run multiple stream servers, even if you do have to change the code a little to allow it. I took a copy of this code a couple of years ago, modified the constructor to accept a port parameter rather than defaulting to a set port, and simply created two stream servers. Not sure if the current code has been updated to allow the same, but it is not difficult to do yourself.

**Comment by oxan** [comment]
Yes, this is possible:

```
uart:
  - id: uart1
    # ...
  - id: uart2
    # ...

stream_server:
  - uart_id: uart1
    port: 5000
  - uart_id: uart2
    port: 5001
```
