### ISSUE TITLE
Stream server not working on software uarts on ESP32

### ISSUE THREAD

**Issue by ficueu** [oxan/esphome-stream-server#29]
Hello, i posted [issue](https://github.com/esphome/issues/issues/4166) in esphome issues tracker but i made more configurations to find more scenarios while stream server is not working. Currently i have configuration while sttream server is not working while is declared more than 3 uarts (including logger on uart) on ESP32. I think it was connected with software uart implementation on ESP32 but i'm don't know how to check if uart is currently software or hardware.
Can anyone confirm that stream server is not working on this config?

```
external_components:
  - source: github://oxan/esphome-stream-server

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: very_verbose

stream_server:
  uart_id: uart_bus3
  port: 1234

uart:
  - id: uart_bus1
    rx_pin: GPIO13
    tx_pin: GPIO14
    baud_rate: 115200
  - id: uart_bus2
    rx_pin: GPIO15
    tx_pin: GPIO16
    baud_rate: 115200
  - id: uart_bus3
    rx_pin: GPIO4
    tx_pin: GPIO5
    baud_rate: 115200
```
