### ISSUE TITLE
Official releases?

### ISSUE THREAD

**Issue by jmartens** [oxan/esphome-stream-server#31]
Could you create official releases or at least tags? That way it is easier to pin streamserver to a specific commit?

In my case it seems my local ESP device is not working with the current tip of master, but it is very hard to downgrade streamserver.

External components only tage branches or tags apparently if I consult the docs at https://esphome.io/components/external_components.html

**Comment by oxan** [comment]
You can actually specify any git ref (including a commit sha) using external components, it's probably documented as branch or tag only to keep it understandable for beginners.

However, actually tagging a release isn't a bad idea. If I do that, it'll be current master though, not an old version.

> In my case it seems my local ESP device is not working with the current tip of master

What's not working?

**Comment by jmartens** [comment]
Somehow I lost all transmission of P1 smart energy meter after january 28th at least no data is present anymore in the Energy panel.

Still debugging why, so far I can see multiple possible causes:
- changes to the serialserver code base since the last working update of my ESP device, hence my request for releases. Will see if working with a commit hash makes any difference, at least I can perhaps pinpoint if it is the code base, at what point in the code base it might be introduced.
- no telegrams are actually transmitted to the ESP device anymore
- ESPHome encryption feature needs implementation
- ... perhaps something else I overlooked

**Comment by jmartens** [comment]
> You can actually specify any git ref (including a commit sha) for external components, it's probably documented as branch or tag to keep it understandable for beginners.

Have not seem to get it working, either:
```
  Remote branch master@43ade65d088d99a6f1bb2da32f7cdd666eb4eb59 not found in upstream origin.
  source: 
    type: git
    url: https://github.com/oxan/esphome-stream-server
    ref: master@43ade65d088d99a6f1bb2da32f7cdd666eb4eb59
```

or 
```
  Remote branch 43ade65d088d99a6f1bb2da32f7cdd666eb4eb59 not found in upstream origin.
  source: 
    type: git
    url: https://github.com/oxan/esphome-stream-server
    ref: 43ade65d088d99a6f1bb2da32f7cdd666eb4eb59
```
when validating/building the yaml.
