### ISSUE TITLE
Can not connect to esphome over ethernet after changes from 22 march 2023

### ISSUE THREAD

**Issue by teklabania** [oxan/esphome-stream-server#37]
Hi, I'm using zigbee coordinator with ESP32 and Ethernet, like [this one](https://forum.arturhome.pl/uploads/default/original/2X/c/cdc821753880c76e0354b70bb1500729793dcf5c.jpeg). Lately I upgraded esphome on the device, and esphome-stream-server was also upgraded. The changes from your commits from 22.03.2023 made me unable to connect to my esphome device. I could only ping it but couldn't connect to web_server on port 80 nor api on port 6053
```
WARNING Can't connect to ESPHome API for device-name.my.domain: Error connecting to ('192.168.1.10', 6053): [Errno 111] Connect call failed ('192.168.1.10', 6053)
```
This is my configuration:
```
substitutions:
  device_name: cc2652p01
  friendly_name: ${device_name} over LAN

esphome:
  name: ${device_name}
  comment: ${friendly_name}
  platform: ESP32
  board: esp-wrover-kit

web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

external_components:
  - source: github://oxan/esphome-stream-server

stream_server:
  uart_id: uart_bus

uart:
  id: uart_bus
  rx_pin: GPIO5
  tx_pin: GPIO17
  baud_rate: 115200
```
I forked your repository and created a tag at a commit `53a7260e0158f99f57763a7e41eb76afac309506` from 07.02.2023, then set up `external_components.source` pointing to my repository with reference to the tag I created and everything works perfectly:
```
external_components:
  - source: github://teklabania/esphome-stream-server@v0.0.1
```
